export const mockLocations = [
  { id: 1, city_name: "Casablanca", map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d106354.29828859187!2d-7.6693946!3d33.5724029!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xda7cd4778aa113b%3A0xb06c106e203251ee!2sCasablanca!5e0!3m2!1sen!2sma!4v1700000000000!5m2!1sen!2sma" },
  { id: 2, city_name: "Marrakech", map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d108702.4278453443!2d-8.0778932!3d31.6225224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xdafee8d9611d6f5%3A0x2ca847f805436f59!2sMarrakech!5e0!3m2!1sen!2sma!4v1700000000000!5m2!1sen!2sma" },
  { id: 3, city_name: "Rabat", map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d105822.42410304313!2d-6.9273024!3d33.9715904!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xda76b872d8471c1%3A0xbec9e309f1a61f10!2sRabat!5e0!3m2!1sen!2sma!4v1700000000000!5m2!1sen!2sma" },
  { id: 4, city_name: "Tangier", map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d103732.18182285145!2d-5.8339543!3d35.7594651!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd0b875cf04c13fd%3A0xec90c3ea2c96c340!2sTangier!5e0!3m2!1sen!2sma!4v1700000000000!5m2!1sen!2sma" }
];

export const mockCars = [
  {
    id: 6,
    name: "Range Rover SV",
    price: 900.00,
    image: "range_rover_sv.png",
    category: "luxury",
    description: {
      ar: "الفخامة والتنوع",
      de: "Luxus und Vielseitigkeit",
      en: "Luxury and versatility",
      es: "Lujo y versatilidad",
      fr: "Luxe et polyvalence",
      it: "Lusso e versatilità",
      ja: "ラグジュアリーと多様性",
      pt: "Luxo e versatilidade",
      ru: "Роскошь и универсальность",
      zh: "豪华与多功能性"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      nl: "Casablanca, Marrakesh, Rabat, Tanger",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰卡，马拉喀什，拉巴特，丹吉尔"
    },
    engine_code: "V8 TT",
    displacement: "4.4",
    horsepower: 615,
    zero_to_hundred: 4.6,
    top_speed: 290,
    drivetrain: "AWD",
    make: "Land Rover"
  },
  {
    id: 7,
    name: "Tesla Model S plaid",
    price: 800.00,
    image: "tesla-model-S-plaid.jpg",
    category: "electric",
    description: {
      ar: "أداء كهربائي فائق",
      de: "Ultimative elektrische Leistung",
      en: "Ultimate electric performance",
      es: "Rendimiento eléctrico definitivo",
      fr: "Performance électrique ultime",
      it: "Prestazioni elettriche estreme",
      ja: "究極の電動パフォーマンス",
      pt: "Desempenho elétrico supremo",
      ru: "Максимальная электрическая производительность",
      zh: "终极电动性能"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      nl: "Casablanca, Marrakesh, Rabat, Tanger",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰卡，马拉喀什，拉巴特，丹吉尔"
    },
    engine_code: "EV",
    displacement: null,
    horsepower: 1020,
    zero_to_hundred: 2.1,
    top_speed: 322,
    drivetrain: "AWD",
    make: "Tesla"
  },
  {
    id: 8,
    name: "Bugatti Chiron Super Sport",
    price: 6000.00,
    image: "bugatti_chron_ss.jpg",
    category: "hypercar",
    description: {
      ar: "قوة قصوى وفخامة فائقة",
      de: "Ultimative Leistung und extremer Luxus",
      en: "Ultimate power and extreme luxury",
      es: "Potencia supreme y lujo extremo",
      fr: "Puissance ultime et luxe extrême",
      it: "Potenza estrema e lusso estremo",
      ja: "究極のパワーと極限のラグジュアリー",
      pt: "Potência máxima e luxo extremo",
      ru: "Максимальная мощность и экстремальная роскошь",
      zh: "终极动力与极致奢华"
    },
    locations: {
      ar: "الدار البيضاء، مراكش",
      de: "Casablanca, Marrakesch",
      en: "Casablanca, Marrakech",
      es: "Casablanca, Marrakech",
      fr: "Casablanca, Marrakech",
      it: "Casablanca, Marrakech",
      ja: "カサブランカ、マラケシュ",
      nl: "Casablanca, Marrakesh",
      pt: "Casablanca, Marrakech",
      ru: "Касабланка, Марракеш",
      zh: "卡萨布兰卡，马拉喀什"
    },
    engine_code: "W16 QT",
    displacement: "8.0",
    horsepower: 1600,
    zero_to_hundred: 2.4,
    top_speed: 440,
    drivetrain: "AWD",
    make: "Bugatti"
  },
  {
    id: 10,
    name: "Audi RS6 Avant",
    price: 900.00,
    image: "rs6_avant.jpg",
    category: "sport",
    description: {
      ar: "أداء وتعدد استخدامات مع الأناقة",
      de: "Leistung und Vielseitigkeit mit Stil",
      en: "Performance and versatility with style",
      es: "Rendimiento y versatilidad con estilo",
      fr: "Performance et polyvalence avec style",
      it: "Prestazioni e versatilità con stile",
      ja: "スタイルを備えたパフォーマンスと多用途性",
      pt: "Desempenho e versatilidade com estilo",
      ru: "Производительность и универсальность со стилем",
      zh: "性能与风格兼备的多功能性"
    },
    locations: {
      ar: "الرباط، طنجة",
      de: "Rabat, Tanger",
      en: "Rabat, Tangier",
      es: "Rabat, Tánger",
      fr: "Rabat, Tanger",
      it: "Rabat, Tangeri",
      ja: "ラバト，タンジール",
      nl: "Rabat, Tanger",
      pt: "Rabat, Tangier",
      ru: "Рабат, Танжер",
      zh: "拉巴特，丹吉尔"
    },
    engine_code: "V8 TT",
    displacement: "4.0",
    horsepower: 600,
    zero_to_hundred: 3.6,
    top_speed: 250,
    drivetrain: "AWD",
    make: "Audi"
  },
  {
    id: 12,
    name: "Aston Martin DBS Superleggera",
    price: 2500.00,
    image: "aston_dbs.jpg",
    category: "supercar",
    description: {
      ar: "أداء خام وتصميم بريطاني",
      de: "Rohe Leistung und britisches Design",
      en: "Raw performance and British design",
      es: "Rendimiento bruto y diseño británico",
      fr: "Performance brute et design britannique",
      it: "Prestazioni grezze e design britannico",
      ja: "圧倒的な性能 & 英国のデザイン",
      pt: "Desempenho bruto e design britânico",
      ru: "Сырая мощь и британский дизайн",
      zh: "原始性能与英伦设计"
    },
    locations: {
      ar: "الدار البيضاء، مراكش",
      de: "Casablanca, Marrakesch",
      en: "Casablanca, Marrakech",
      es: "Casablanca, Marrakech",
      fr: "Casablanca, Marrakech",
      it: "Casablanca, Marrakech",
      ja: "カサブランカ，マラケシュ",
      nl: "Casablanca, Marrakesh",
      pt: "Casablanca, Marrakech",
      ru: "Касабланка, Марракеш",
      zh: "卡萨布兰卡，马拉喀什"
    },
    engine_code: "V12 TT",
    displacement: "5.2",
    horsepower: 725,
    zero_to_hundred: 3.4,
    top_speed: 340,
    drivetrain: "RWD",
    make: "Aston Martin"
  },
  {
    id: 13,
    name: "McLaren 720S",
    price: 4500.00,
    image: "mclaren_720s.jpg",
    category: "hypercar",
    description: {
      ar: "تقنية متقدمة وأداء استثنائي",
      de: "Spitzenleistungstechnologie und außergewöhnliche Leistung",
      en: "Cutting-edge technology and exceptional performance",
      es: "Tecnología de vanguardia y un rendimiento excepcional",
      fr: "Technologie de pointe et performances exceptionnelles",
      it: "Tecnologia all'avanguardia e prestazioni eccezionali",
      ja: "最先端技術と卓越した性能",
      pt: "Tecnologia de ponta e desempenho excepcional",
      ru: "Передовые технологии и исключительная производительность",
      zh: "尖端技术与卓越性能"
    },
    locations: {
      ar: "مراكش، الرباط",
      de: "Marrakesch, Rabat",
      en: "Marrakech, Rabat",
      es: "Marrakech, Rabat",
      fr: "Marrakech, Rabat",
      it: "Marrakech, Rabat",
      ja: "マラケシュ，ラバト",
      nl: "Marrakesh, Rabat",
      pt: "Marrakech, Rabate",
      ru: "Марракеш, Рабат",
      zh: "马拉喀什，拉巴特"
    },
    engine_code: "V8 TT",
    displacement: "4.0",
    horsepower: 720,
    zero_to_hundred: 2.9,
    top_speed: 341,
    drivetrain: "RWD",
    make: "McLaren"
  },
  {
    id: 14,
    name: "Rolls-Royce Cullinan",
    price: 8500.00,
    image: "rolls_royce_cullinan.jpg",
    category: "luxury",
    description: {
      ar: "ترف مطلق وراحة ملكية",
      de: "Absoluter Luxus und königlicher Komfort",
      en: "Absolute luxury and royal comfort",
      es: "Lujo absoluto y confort real",
      fr: "Luxe absolu et confort royal",
      it: "Lusso assoluto e comfort reale",
      ja: "絶対的な贅沢と王室の快適さ",
      pt: "Luxo absoluto e conforto real",
      ru: "Абсолютная роскошь и королевский комфорт",
      zh: "绝对奢华与皇家舒适"
    },
    locations: {
      ar: "الدار البيضاء، الرباط، طنجة",
      de: "Casablanca, Rabat, Tanger",
      en: "Casablanca, Rabat, Tangier",
      es: "Casablanca, Rabat, Tánger",
      fr: "Casablanca, Rabat, Tanger",
      it: "Casablanca, Rabat, Tangeri",
      ja: "カサブランカ，ラバト，タンジール",
      nl: "Casablanca, Rabat, Tanger",
      pt: "Casablanca, Rabate, Tangier",
      ru: "Касабланка, Рабат, Танжер",
      zh: "卡萨布兰卡，拉巴特，丹吉尔"
    },
    engine_code: "V12 TT",
    displacement: "6.8",
    horsepower: 571,
    zero_to_hundred: 5.2,
    top_speed: 250,
    drivetrain: "AWD",
    make: "Rolls-Royce"
  },
  {
    id: 17,
    name: "Koenigsegg Agera RS",
    price: 20000.00,
    image: "koenigsegg_agera.jpg",
    category: "hypercar",
    description: {
      ar: "سرعة وتقنية لا مثيل لها",
      de: "Unvergleichliche Geschwindigkeit und Technologie",
      en: "Unmatched speed and technology",
      es: "Velocidad y tecnología incomparables",
      fr: "Vitesse et technologie incomparables",
      it: "Velocità e tecnologia incomparabili",
      ja: "比類のない速度と技術",
      pt: "Velocidade e tecnologia incomparáveis",
      ru: "Несравненная скорость и технологии",
      zh: "无与伦比的速度和技术"
    },
    locations: {
      ar: "الدار البيضاء",
      de: "Casablanca",
      en: "Casablanca",
      es: "Casablanca",
      fr: "Casablanca",
      it: "Casablanca",
      ja: "カサブランカ",
      nl: "Casablanca",
      pt: "Casablanca",
      ru: "Касабланка",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "5.0",
    horsepower: 1160,
    zero_to_hundred: 2.8,
    top_speed: 447,
    drivetrain: "RWD",
    make: "Koenigsegg"
  },
  {
    id: 18,
    name: "Chevrolet Corvette Stingray",
    price: 1200.00,
    image: "corvette_stingray.jpg",
    category: "sport",
    description: {
      ar: "الأداء الأمريكي والتصميم الأيقوني",
      de: "Amerikanische Leistung und ikonisches Design",
      en: "American performance and iconic design",
      es: "Rendimiento americano y diseño icónico",
      fr: "Performance américaine et design iconique",
      it: "Prestazioni americane e design iconico",
      ja: "アメリカンパフォーマンスと象徴的なデザイン",
      pt: "Desempenho americano e design icônico",
      ru: "Американская производительность и культовый дизайн",
      zh: "美国性能与标志性设计"
    },
    locations: {
      ar: "الدار البيضاء، الرباط، مراكش",
      de: "Casablanca, Rabat, Marrakesch",
      en: "Casablanca, Rabat, Marrakech",
      es: "Casablanca, Rabat, Marrakech",
      fr: "Casablanca, Rabat, Marrakech",
      it: "Casablanca, Rabat, Marrakech",
      ja: "カサブランカ，ラバト，マラケシュ",
      nl: "Casablanca, Rabat, Marrakesh",
      pt: "Casablanca, Rabat, Marrakech",
      ru: "Касабланка, Рабат, Марракеш",
      zh: "卡萨布兰卡，拉巴特，马拉喀什"
    },
    engine_code: "V8 NA",
    displacement: "6.2",
    horsepower: 495,
    zero_to_hundred: 2.9,
    top_speed: 312,
    drivetrain: "RWD",
    make: "Chevrolet"
  },
  {
    id: 20,
    name: "Nissan GT-R",
    price: 1800.00,
    image: "nissan_gt_r.jpg",
    category: "sport",
    description: {
      ar: "أداء أسطوري وتقنية يابانية",
      de: "Legendäre Leistung und japanische Technologie",
      en: "Legendary performance and Japanese technology",
      es: "Rendimiento legendario y tecnología japonesa",
      fr: "Performance de légende et technologie japonaise",
      it: "Prestazioni leggendarie e tecnologia giapponese",
      ja: "伝説的な性能と日本の技術",
      pt: "Desempenho lendário e tecnologia japonesa",
      ru: "Легендарные характеристики и японская технология",
      zh: "传奇性能和日本技术"
    },
    locations: {
      ar: "مراكش، الدار البيضاء",
      de: "Marrakesch, Casablanca",
      en: "Marrakech, Casablanca",
      es: "Marrakech, Casablanca",
      fr: "Marrakech, Casablanca",
      it: "Marrakech, Casablanca",
      ja: "マラケシュ，カサブランカ",
      nl: "Marrakesh, Casablanca",
      pt: "Marrakech, Casablanca",
      ru: "Маракеш, Касабланка",
      zh: "马拉喀什，卡萨布兰卡"
    },
    engine_code: "V6 TT",
    displacement: "3.8",
    horsepower: 570,
    zero_to_hundred: 2.8,
    top_speed: 315,
    drivetrain: "AWD",
    make: "Nissan"
  },
  {
    id: 21,
    name: "Jaguar F-Type",
    price: 2000.00,
    image: "jaguar_f_type.jpg",
    category: "sport",
    description: {
      ar: "الأداء والتصميم البريطاني",
      de: "Britische Leistung und Design",
      en: "British performance and design",
      es: "Rendimiento y diseño británicos",
      fr: "Performance et design britanniques",
      it: "Prestazioni e design britannici",
      ja: "英国のパフォーマンスとデザイン",
      pt: "Desempenho e design britânicos",
      ru: "Британская производительность и дизайн",
      zh: "英国性能与设计"
    },
    locations: {
      ar: "الرباط، طنجة",
      de: "Rabat, Tanger",
      en: "Rabat, Tangier",
      es: "Rabat, Tánger",
      fr: "Rabat, Tanger",
      it: "Rabat, Tangeri",
      ja: "ラバト，タンジール",
      nl: "Rabat, Tanger",
      pt: "Rabat, Tangier",
      ru: "Рабат, Танжер",
      zh: "拉巴特，丹吉尔"
    },
    engine_code: "V8 S",
    displacement: "5.0",
    horsepower: 575,
    zero_to_hundred: 3.7,
    top_speed: 300,
    drivetrain: "AWD",
    make: "Jaguar"
  },
  {
    id: 22,
    name: "BMW M5",
    price: 2200.00,
    image: "bmw_m5.jpg",
    category: "sport",
    description: {
      ar: "القوة والفخامة متحدتان",
      de: "Leistung und Luxus vereint",
      en: "Power and luxury united",
      es: "Poder y lujo unidos",
      fr: "La puissance et le luxe réunis",
      it: "Potenza e lusso uniti",
      ja: "力と豪華の融合",
      pt: "Poder e luxo unidos",
      ru: "Сила и роскошь объединены",
      zh: "力量与奢华结合"
    },
    locations: {
      ar: "الدار البيضاء، مراكش",
      de: "Casablanca, Marrakesch",
      en: "Casablanca, Marrakech",
      es: "Casablanca, Marrakech",
      fr: "Casablanca, Marrakech",
      it: "Casablanca, Marrakech",
      ja: "カサブランカ，マラケシュ",
      nl: "Casablanca, Marrakesh",
      pt: "Casablanca, Marrakech",
      ru: "Касабланка, Марракеш",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "4.4",
    horsepower: 600,
    zero_to_hundred: 3.4,
    top_speed: 250,
    drivetrain: "AWD",
    make: "BMW"
  },
  {
    id: 23,
    name: "Audi R8",
    price: 3000.00,
    image: "audi_r8.jpg",
    category: "supercar",
    description: {
      ar: "الأداء والفخامة والتكنولوجيا",
      de: "Leistung, Luxus und Technologie",
      en: "Performance, luxury, and technology",
      es: "Rendimiento, lujo y tecnología",
      fr: "Performance, luxe et technologie",
      it: "Prestazioni, lusso e tecnologia",
      ja: "パフォーマンス、ラグジュアリー、テクノロジー",
      pt: "Desempenho, luxo e tecnologia",
      ru: "Производительность, роскошь и технологии",
      zh: "性能、奢华与技术"
    },
    locations: {
      ar: "الدار البيضاء، الرباط",
      de: "Casablanca, Rabat",
      en: "Casablanca, Rabat",
      es: "Casablanca, Rabat",
      fr: "Casablanca, Rabat",
      it: "Casablanca, Rabat",
      ja: "カサブランカ，ラバト",
      nl: "Casablanca, Rabat",
      pt: "Casablanca, Rabate",
      ru: "Касабланка, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V10 NA",
    displacement: "5.2",
    horsepower: 620,
    zero_to_hundred: 3.1,
    top_speed: 331,
    drivetrain: "AWD",
    make: "Audi"
  },
  {
    id: 24,
    name: "Ford Mustang GT",
    price: 1500.00,
    image: "mustang_gt.jpg",
    category: "sport",
    description: {
      ar: "رمز أمريكي مع أداء عنيف",
      de: "Amerikanische Ikone mit brutaler Leistung",
      en: "American icon with brutal performance",
      es: "Ícono americano con un rendimiento brutal",
      fr: "Icône américaine avec des performances brutales",
      it: "Icona americana con prestazioni brutali",
      ja: "アメリカのアイコンと猛烈なパフォーマンス",
      pt: "Ícone americano com desempenho brutal",
      ru: "Американская икона с жесткой производительностью",
      zh: "拥有野性性能的美国偶像"
    },
    locations: {
      ar: "الدار البيضاء، الرباط",
      de: "Casablanca, Rabat",
      en: "Casablanca, Rabat",
      es: "Casablanca, Rabat",
      fr: "Casablanca, Rabat",
      it: "Casablanca, Rabat",
      ja: "カサブランカ，ラバト",
      nl: "Casablanca, Rabat",
      pt: "Casablanca, Rabate",
      ru: "Касабланка, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 NA",
    displacement: "5.0",
    horsepower: 450,
    zero_to_hundred: 4.3,
    top_speed: 250,
    drivetrain: "RWD",
    make: "Ford"
  },
  {
    id: 2,
    name: "Honda NSX",
    price: 2500.00,
    image: "honda_nsx.jpeg",
    category: "sport",
    description: {
      ar: "هندسة متقدمة وأداء أسطوري",
      de: "Spitzentechnologie und legendäre Leistung",
      en: "Cutting-edge engineering and legendary performance",
      es: "Ingeniería de vanguardia y rendimiento legendario",
      fr: "Ingénierie de pointe et performance légendaire",
      it: "Ingegneria all'avanguardia e prestazioni leggendarie",
      ja: "最先端の技術と伝説的なパフォーマンス",
      pt: "Engenharia de ponta e desempenho lendário",
      ru: "Передовые технологии и легендарная производительность",
      zh: "尖端工程与传奇性能"
    },
    locations: {
      ar: "الدار البيضاء، الرباط",
      de: "Casablanca, Rabat",
      en: "Casablanca, Rabat",
      es: "Casablanca, Rabat",
      fr: "Casablanca, Rabat",
      it: "Casablanca, Rabat",
      ja: "カサブランカ、ラバト",
      pt: "Casablanca, Rabate",
      ru: "Касабланка, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V6 TT",
    displacement: "3.5",
    horsepower: 581,
    zero_to_hundred: 3.0,
    top_speed: 308,
    drivetrain: "AWD",
    make: "Honda"
  },
  {
    id: 3,
    name: "Mercedes-AMG GT",
    price: 1000.00,
    image: "amg_gt.jpg",
    category: "sport",
    description: {
      ar: "الأناقة والأداء",
      de: "Eleganz und Leistung",
      en: "Elegance and performance",
      es: "Elegancia y rendimiento",
      fr: "Élégance et performance",
      it: "Eleganza e prestazioni",
      ja: "エレガンスとパフォーマンス",
      pt: "Elegância e desempenho",
      ru: "Элегантность и производительность",
      zh: "优雅与性能"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      nl: "Casablanca, Marrakesh, Rabat, Tanger",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰كا"
    },
    engine_code: "V8 TT",
    displacement: "4.0",
    horsepower: 530,
    zero_to_hundred: 3.8,
    top_speed: 312,
    drivetrain: "RWD",
    make: "Mercedes-AMG"
  },
  {
    id: 27,
    name: "Maserati Levante",
    price: 2000.00,
    image: "maserati_levante.jpg",
    category: "luxury",
    description: {
      ar: "الفخامة والأداء على جميع التضاريس",
      de: "Luxus und Leistung auf allen Terrainarten",
      en: "Luxury and performance on all terrains",
      es: "Lujo y rendimiento en todo tipo de terrenos",
      fr: "Luxe et performance sur tous terrains",
      it: "Lusso e performance su tutti i terreni",
      ja: "すべての地形でのラグジュアリーとパフォーマンス",
      pt: "Luxo e desempenho em todos os terrenos",
      ru: "Роскошь и производительность на любых территориях",
      zh: "全地形的奢华与性能"
    },
    locations: {
      ar: "مراكش، الدار البيضاء",
      de: "Marrakesch, Casablanca",
      en: "Marrakech, Casablanca",
      es: "Marrakech, Casablanca",
      fr: "Marrakech, Casablanca",
      it: "Marrakech, Casablanca",
      ja: "マラケシュ，カサブランカ",
      nl: "Marrakesh, Casablanca",
      pt: "Marrakech, Casablanca",
      ru: "Марракеш, Касабланка",
      zh: "马拉喀什，卡萨布兰ка"
    },
    engine_code: "V6 TT",
    displacement: "3.0",
    horsepower: 350,
    zero_to_hundred: 6.0,
    top_speed: 251,
    drivetrain: "AWD",
    make: "Maserati"
  },
  {
    id: 1,
    name: "Porsche 911 GT3",
    price: 1200.00,
    image: "911_gt3.jpg",
    category: "sport",
    description: {
      ar: "التميّز الهندسي الألماني",
      de: "Deutsche Ingenieurskunst auf höchstem Niveau",
      en: "German engineering excellence",
      es: "Excelencia de la ingeniería alemana",
      fr: "L’excellence de l’ingénierie allemande",
      it: "L’eccellenza dell’ingegneria tedesca",
      ja: "ドイツの卓越したエンジニアリング",
      pt: "Excelência da engenharia alemã",
      ru: "Немецкое инженерное превосходство",
      zh: "德国工程卓越品质"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰ка"
    },
    engine_code: "F6 NA",
    displacement: "4.0",
    horsepower: 510,
    zero_to_hundred: 3.4,
    top_speed: 318,
    drivetrain: "RWD",
    make: "Porsche"
  },
  {
    id: 4,
    name: "BMW X7",
    price: 700.00,
    image: "bmw_x7.png",
    category: "luxury",
    description: {
      ar: "راحة عائلية فاخرة",
      de: "Premium-Familienkomfort",
      en: "Premium family comfort",
      es: "Comodidad familiar premium",
      fr: "Confort familial premium",
      it: "Comfort familiare premium",
      ja: "プレミアムな家族の快適さ",
      pt: "Conforto familiar premium",
      ru: "Премиальный семейный komfort",
      zh: "高端家庭舒适"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      nl: "Casablanca, Marrakesh, Rabat, Tanger",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰ка"
    },
    engine_code: "I6 TT",
    displacement: "3.0",
    horsepower: 381,
    zero_to_hundred: 5.8,
    top_speed: 250,
    drivetrain: "AWD",
    make: "BMW"
  },
  {
    id: 28,
    name: "McLaren P1",
    price: 10000.00,
    image: "mclaren_p1.jpg",
    category: "hypercar",
    description: {
      ar: "تكنولوجيا هجينة وأداء سيارة خارقة",
      de: "Hybride Technologie und Supercar-Leistung",
      en: "Hybrid technology and supercar performance",
      es: "Tecnología híbrida y rendimiento de supercoche",
      fr: "Technologie hybride et performance de supercar",
      it: "Tecnologia ibrida e performance da supercar",
      ja: "ハイブリッド技術とスーパーカー性能",
      pt: "Tecnologia híbrida e desempenho de supercarro",
      ru: "Гибридная технология и производительность суперкара",
      zh: "混合动力技术与超级跑车性能"
    },
    locations: {
      ar: "الدار البيضاء",
      de: "Casablanca",
      en: "Casablanca",
      es: "Casablanca",
      fr: "Casablanca",
      it: "Casablanca",
      ja: "カサブランカ",
      nl: "Casablanca",
      pt: "Casablanca",
      ru: "Касабланка",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "3.8",
    horsepower: 916,
    zero_to_hundred: 2.8,
    top_speed: 350,
    drivetrain: "RWD",
    make: "McLaren"
  },
  {
    id: 29,
    name: "Ferrari F8 Tributo",
    price: 5000.00,
    image: "ferrari_f8_tributo.jpg",
    category: "supercar",
    description: {
      ar: "سرعة وتصميم وصوت لا مثيل لهم",
      de: "Unvergleichliche Geschwindigkeit, Design und Klang",
      en: "Unmatched speed, design, and sound",
      es: "Velocidad, diseño y sonido inigualables",
      fr: "Vitesse, design et son inégalés",
      it: "Velocità, design e suono impareggiabili",
      ja: "比類のない速度、デザイン、サウンド",
      pt: "Velocidade, design e som incomparáveis",
      ru: "Несравненная скорость, дизайн и звук",
      zh: "无与伦比的速度、设计和声音"
    },
    locations: {
      ar: "مراكش، الدار البيضاء",
      de: "Marrakesch, Casablanca",
      en: "Marrakech, Casablanca",
      es: "Marrakech, Casablanca",
      fr: "Marrakech, Casablanca",
      it: "Marrakech, Casablanca",
      ja: "マラケシュ，カサブランカ",
      nl: "Marrakesh, Casablanca",
      pt: "Marrakech, Casablanca",
      ru: "Марракеш, Касабланка",
      zh: "马拉喀什，卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "3.9",
    horsepower: 720,
    zero_to_hundred: 2.9,
    top_speed: 340,
    drivetrain: "RWD",
    make: "Ferrari"
  },
  {
    id: 30,
    name: "Ferrari 488 GTB",
    price: 2500.00,
    image: "ferrari_488_gtb.jpg",
    category: "sport",
    description: {
      ar: "الأناقة الإيطالية مقرونة بأداء استثنائي",
      de: "Italienische Eleganz kombiniert mit außergewöhnlicher Leistung",
      en: "Italian elegance combined with extraordinary performance",
      es: "La elegancia italiana combinada con un rendimiento extraordinario",
      fr: "L'élégance italienne alliée à une performance hors norme",
      it: "Eleganza italiana combinata con prestazioni straordinarie",
      ja: "並外れたパフォーマンスを持つイタリアンエレガンス",
      pt: "Elegância extraordinária",
      ru: "Итальянская элегантность в сочетании с характеристиками",
      zh: "意大利优雅与非凡性能"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط",
      de: "Casablanca, Marrakesch, Rabat",
      en: "Casablanca, Marrakech, Rabat",
      es: "Casablanca, Marrakech, Rabat",
      fr: "Casablanca, Marrakech, Rabat",
      it: "Casablanca, Marrakech, Rabat",
      ja: "カサブランカ，マラケシュ，ラバト",
      nl: "Casablanca, Marrakesh, Rabat",
      pt: "Casablanca, Marrakech, Rabate",
      ru: "Касабланка, Марракеش, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "3.9",
    horsepower: 670,
    zero_to_hundred: 3.0,
    top_speed: 330,
    drivetrain: "RWD",
    make: "Ferrari"
  },
  {
    id: 16,
    name: "Pagani Huayra",
    price: 15000.00,
    image: "pagani_huayra.jpg",
    category: "hypercar",
    description: {
      ar: "فن الأداء والتفرد",
      de: "Die Kunst der Leistung und Exklusivität",
      en: "The art of performance and exclusivity",
      es: "El arte del rendimiento y la exclusividad",
      fr: "L'art de la performance et de l'exclusivité",
      it: "L'arte delle prestazioni e dell'esclusività",
      ja: "パフォーマンスと独自性の芸術",
      pt: "A arte de desempenho e exclusividade",
      ru: "Искусство производительности и эксклюзивности",
      zh: "性能与独特性的艺术"
    },
    locations: {
      ar: "الدار البيضاء",
      de: "Casablanca",
      en: "Casablanca",
      es: "Casablanca",
      fr: "Casablanca",
      it: "Casablanca",
      ja: "カサブランカ",
      nl: "Casablanca",
      pt: "Casablanca",
      ru: "Касабланка",
      zh: "卡萨布兰ка"
    },
    engine_code: "V12 TT",
    displacement: "6.0",
    horsepower: 730,
    zero_to_hundred: 3.3,
    top_speed: 360,
    drivetrain: "RWD",
    make: "Pagani"
  },
  {
    id: 31,
    name: "Mercedes G63",
    price: 850.00,
    image: "Mercede_G63.jpg",
    category: "custom",
    description: {
      ar: "التميّز الهندسي الألماني",
      de: "Deutsche Ingenieurskunst auf höchstem Niveau",
      en: "German engineering excellence",
      es: "Excelencia de la ingeniería alemana",
      fr: "L’excellence de l’ingénierie allemande",
      it: "L’eccellenza dell’ingegneria tedesca",
      ja: "ドイツの卓越したエンジニアリング",
      pt: "Excelência da engenharia alemã",
      ru: "Немецкое инженерное превосходство",
      zh: "德国工程卓越品质"
    },
    locations: {
      ar: "الدار البيضاء، الرباط، طنجة",
      de: "Casablanca, Rabat, Tanger",
      en: "Casablanca, Rabat, Tangier",
      es: "Casablanca, Rabat, Tánger",
      fr: "Casablanca, Rabat, Tanger",
      it: "Casablanca, Rabat, Tangeri",
      ja: "カサブランカ、ラバト、タンジェ",
      pt: "Casablanca, Rabat, Tânger",
      ru: "Касабланка, Рабат, Танжер",
      zh: "卡萨布兰ка"
    },
    engine_code: "V8 TT",
    displacement: "4.0",
    horsepower: 585,
    zero_to_hundred: 4.5,
    top_speed: 240,
    drivetrain: "AWD",
    make: "Mercedes"
  },
  {
    id: 15,
    name: "Bentley Continental GT",
    price: 5000.00,
    image: "bentley_continental_gt.jpg",
    category: "luxury",
    description: {
      ar: "ترف وأداء",
      de: "Luxus und Leistung",
      en: "Luxury and performance",
      es: "Lujo y rendimiento",
      fr: "Luxe et performance",
      it: "Lusso e prestazioni",
      ja: "ラグジュアリーとパフォーマンス",
      pt: "Luxo e desempenho",
      ru: "Роскошь и производительность",
      zh: "奢华与性能"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط",
      de: "Casablanca, Marrakesch, Rabat",
      en: "Casablanca, Marrakech, Rabat",
      es: "Casablanca, Marrakech, Rabat",
      fr: "Casablanca, Marrakech, Rabat",
      it: "Casablanca, Marrakech, Rabat",
      ja: "カサブランカ，マラケシュ，ラバト",
      nl: "Casablanca, Marrakesh, Rabat",
      pt: "Casablanca, Marrakech, Rabate",
      ru: "Касабланка, Марракеш, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "W12 TT",
    displacement: "6.0",
    horsepower: 659,
    zero_to_hundred: 3.6,
    top_speed: 335,
    drivetrain: "AWD",
    make: "Bentley"
  },
  {
    id: 19,
    name: "Toyota Land Cruiser",
    price: 600.00,
    image: "land_cruiser.jpg",
    category: "luxury",
    description: {
      ar: "الصلابة والموثوقية على الطرق الوعرة",
      de: "Robustheit und Geländetauglichkeit",
      en: "Robustness and off-road reliability",
      es: "Robustez y fiabilidad todoterreno",
      fr: "Robustesse et fiabilité tout-terrain",
      it: "Robustezza e affidabilità off-road",
      ja: "堅牢性とオフロード信頼性",
      pt: "Robustez e confiabilidade fora de estrada",
      ru: "Прочность и надежность на бездорожье",
      zh: "越野耐用性和可靠性"
    },
    locations: {
      ar: "الدار البيضاء، الرباط",
      de: "Casablanca, Rabat",
      en: "Casablanca, Rabat",
      es: "Casablanca, Rabat",
      fr: "Casablanca, Rabat",
      it: "Casablanca, Rabat",
      ja: "カサブランカ，ラバト",
      nl: "Casablanca, Rabat",
      pt: "Casablanca, Rabat",
      ru: "Касабланка, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V6 TT",
    displacement: "3.4",
    horsepower: 415,
    zero_to_hundred: 6.7,
    top_speed: 210,
    drivetrain: "AWD",
    make: "Toyota"
  },
  {
    id: 11,
    name: "Ferrari 812 Superfast",
    price: 3500.00,
    image: "ferrari_812.jpg",
    category: "supercar",
    description: {
      ar: "سرعة وأناقة لا مثيل لهما",
      de: "Unvergleichliche Geschwindigkeit und Eleganz",
      en: "Unmatched speed and elegance",
      es: "Velocidad y elegancia incomparables",
      fr: "Vitesse et élégance inégalées",
      it: "Velocità ed eleganza senza pari",
      ja: "比類なきスピードとエレガンス",
      pt: "Velocidade e elegância incomparáveis",
      ru: "Несравненная скорость и элегантность",
      zh: "无与伦比的速度与优雅"
    },
    locations: {
      ar: "الدار البيضاء، الرباط",
      de: "Casablanca, Rabat",
      en: "Casablanca, Rabat",
      es: "Casablanca, Rabat",
      fr: "Casablanca, Rabat",
      it: "Casablanca, Rabat",
      ja: "カサブランカ，ラバト",
      nl: "Casablanca, Rabat",
      pt: "Casablanca, Rabate",
      ru: "Касабланка, Рабат",
      zh: "卡萨布兰ка"
    },
    engine_code: "V12 NA",
    displacement: "6.5",
    horsepower: 800,
    zero_to_hundred: 2.9,
    top_speed: 340,
    drivetrain: "RWD",
    make: "Ferrari"
  },
  {
    id: 5,
    name: "Lamborghini Huracán",
    price: 1500.00,
    image: "lambo_huracan.jpg",
    category: "sport",
    description: {
      ar: "قوة خالصة وتصميم إيطالي",
      de: "Reine Kraft und italienisches Design",
      en: "Pure power and Italian design",
      es: "Potencia pura y diseño italiano",
      fr: "Puissance pure et design italien",
      it: "Potenza pura e design italiano",
      ja: "純粋なパワーとイタリアンデザイン",
      pt: "Potência pura e design italiano",
      ru: "Чистая мощь и итальянский дизайн",
      zh: "纯粹的力量和意大利设计"
    },
    locations: {
      ar: "الدار البيضاء، مراكش، الرباط، طنجة",
      de: "Casablanca, Marrakesch, Rabat, Tanger",
      en: "Casablanca, Marrakech, Rabat, Tangier",
      es: "Casablanca, Marrakech, Rabat, Tánger",
      fr: "Casablanca, Marrakech, Rabat, Tanger",
      it: "Casablanca, Marrakech, Rabat, Tangeri",
      ja: "カサブランカ、マラケシュ、ラバト、タンジール",
      nl: "Casablanca, Marrakesh, Rabat, Tanger",
      pt: "Casablanca, Marrakech, Rabate, Tangier",
      ru: "Касабланка, Марракеш, Рабат, Танжер",
      zh: "卡萨布兰ка"
    },
    engine_code: "V10 NA",
    displacement: "5.2",
    horsepower: 640,
    zero_to_hundred: 2.9,
    top_speed: 325,
    drivetrain: "AWD",
    make: "Lamborghini"
  },
  {
    id: 26,
    name: "Alfa Romeo Giulia Quadrifoglio",
    price: 1700.00,
    image: "alfa_romeo_giulia.jpg",
    category: "sport",
    description: {
      ar: "توازن مثالي بين الأداء والأناقة الإيطالية",
      de: "Perfekte Balance zwischen Leistung und italienischem Stil",
      en: "Perfect balance between performance and Italian style",
      es: "Equilibrio perfecto entre rendimiento y estilo italiano",
      fr: "Équilibre parfait entre performance et style italien",
      it: "Equilibrio perfetto tra prestazioni e stile italiano",
      ja: "パフォーマンスとイタリアンスタイルの完璧なバランス",
      pt: "Equilíbrio perfeito entre desempenho e estilo italiano",
      ru: "Идеальный balance",
      zh: "性能与意大利风格"
    },
    locations: {
      ar: "مراكش، الرباط",
      de: "Marrakesch, Rabat",
      en: "Marrakech, Rabat",
      es: "Marrakech, Rabat",
      fr: "Marrakech, Rabat",
      it: "Marrakech, Rabat",
      ja: "マラケシュ，ラバト",
      nl: "Marrakesh, Rabat",
      pt: "Marrakech, Rabate",
      ru: "Марракеш, Рабат",
      zh: "马拉喀什，拉巴特"
    },
    engine_code: "V6 TT",
    displacement: "2.9",
    horsepower: 510,
    zero_to_hundred: 3.9,
    top_speed: 307,
    drivetrain: "RWD",
    make: "Alfa Romeo"
  }
];

// In-Memory User Store (Initial Admins & VIPs)
export const mockClients = [
  {
    id: 1,
    first_name: "Admin",
    last_name: "Concierge",
    email: "admin@autolux.com",
    password: "$2b$10$wEHLKq2wIqC6XkLh/Wl5eOq6XJocX769VzC/fM9R.J73XyD6s0V9e", // hashed 'admin123'
    role: "admin",
    phone: "+212 522 00 11 22",
    created_at: new Date()
  },
  {
    id: 2,
    first_name: "Yassine",
    last_name: "Real",
    email: "client@autolux.com",
    password: "$2b$10$wEHLKq2wIqC6XkLh/Wl5eOq6XJocX769VzC/fM9R.J73XyD6s0V9e", // hashed 'admin123'
    role: "client",
    phone: "+212 600 11 22 33",
    created_at: new Date()
  }
];

// Physical units for cars (automatically creates units for each car)
export const mockCarUnits = mockCars.flatMap((car, index) => [
  {
    id: index * 2 + 1,
    car_id: car.id,
    color: "Nero Carbonio",
    vin: `VIN-${car.make.substring(0,3).toUpperCase()}-${Math.floor(Math.random() * 900000 + 100000)}`,
    mileage: 2400,
    status: "available"
  },
  {
    id: index * 2 + 2,
    car_id: car.id,
    color: "Bianco Fuji",
    vin: `VIN-${car.make.substring(0,3).toUpperCase()}-${Math.floor(Math.random() * 900000 + 100000)}`,
    mileage: 8900,
    status: index % 5 === 0 ? "rented" : "available"
  }
]);

// 3D Models Config
export const mockModels = [
  {
    id: 1,
    car_id: 26, // Alfa Romeo
    file_path: "alfa_romeo_giulia_quadrifoglio.glb",
    scale_x: 1.0,
    rot_y: 0.0
  },
  {
    id: 2,
    car_id: 1, // Porsche 911 GT3
    file_path: "porsche_911_gt3.glb",
    scale_x: 1.05,
    rot_y: 3.14
  }
];

// Car Parts
export const mockCarParts = [
  { id: 1, car_id: 26, part_name: "Front Bumper", part_type: "body" },
  { id: 2, car_id: 26, part_name: "Carbon Strip", part_type: "strip" },
  { id: 3, car_id: 1, part_name: "Aerodynamic Bumper", part_type: "body" }
];

// Mock Active/Completed Rentals
export const mockRentals = [
  {
    id: 1,
    client_id: 2,
    car_id: 2, // Mercedes unit
    rental_start: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    rental_end: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    price: 3400.00,
    status: "rented",
    location_id: 1,
    created_at: new Date()
  },
  {
    id: 2,
    client_id: 2,
    car_id: 1, // Porsche unit
    rental_start: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    rental_end: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    price: 6000.00,
    status: "completed",
    location_id: 2,
    created_at: new Date()
  }
];
